language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="nebo15"
  - MAIN_BRANCHES="master develop"
  - secure: UsC6twXDHKmpo63h3Y1nStdUXk1iVxXgcQBTJmWGU4wlz72xMOqfJhGRC4YCLKJXzSF7r2djxRCRJNLyGaw/h1hf3nJoEpS1vBq06CxiaF8KNktNzrSl4hAzcnlpecu+2Qwb8adba4s3PPDjkDTtaIa9ZqfL37DzAomttQmWRKyWzVU+7goSEGj19Rjn7f0i/NxPBZulRoOQM+cmb/sEj6uMr2FYf2bd4seli2rsl5jvx6bgdH+fU+k8pkx5uxKMYSFOLbnDAALOcRo+d2Qg4F6NIjFhDl/7xPxF6x1UzNx/zv361PqA9MWE+n/KDkl894GuxmJfsbQrsx0eKEKF7wEOynOyhsiKDF5Z0xoRhiiPRDC51MYh5srEdM/Pca6KCbayxSzrWW9ratNAa37wpwgEBw35ZtgsMWUuCIsTNTE58/YZbE+zmZp8X0lpvURAo9ErdJyBIBLtOqPw+WpiMm4EiZIY2ed2KRVhVrWsqjXbfQnTaWqGFHgR9h87uIJGbp50oypG+byPSA7jlp+lqQkhob7bfJ5AGkdVQibc8aRr1TpmVXPqH1Vgpl6TfZ+GvTSj5aEVC5etOReY3pmvrnCFqVKzc+hUBNStG73nXqesvWxgZPAUDVUzgomATwdYyVY8ehjtM8guHcyv7iNYWRRMiXUNd1JaVcjeqoS1R98=
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- ./bin/version-increment.sh
- ./bin/build.sh
- ./bin/start.sh
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs nsz.web --details
  --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- ./bin/ci/push.sh
