language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master v0.1"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop v0.1"
  # DOCKER_USERNAME DOCKER_PASSWORD
  - secure: "Iq+UX6Rlg7MGIPBOOBPEgLPjm8ZDnBUdAQEnXU7QItSWT5sjaB5s3nvuBboE2STwfSJAalrjnJDZo28wmWCcRPiIeCuODYqF7jxfBZhe+nDvXUozEfcC1PUwizh5LxIT7zcb3W943XQJ6iQAeq24KDM5AKHjV3mgLBwwql+ViC8H6dOP3ILkqiGnn1X+DikmV1ddceS4nrftAT2fIwYwuunWIMxUr/QoHn6XthoQTpigrHVYLAz4JVCaVAETFZnsmOJKfNcs7SoDLBmsNf3nkuLAuSJsRbRMftYAwc7xYLfjGuppeP0EldOxcshiPT7Wr/v1cMFgscKch2XuZ5JhnHcys4PV22e5oufveIX+DwTu0Y4WchyyLAV4DB/unGoCmD59mpJlNnt8XDuaZHkYCzBB/FgDnJ169uXeCDZm0xigOSvuVkctbv7SgL9pRk8IdLpkvDz1LBIORPqB96rV0vGGCfwMadsb6DGR/Movlfu6HP1Dp/TIcet8oiQa9sM0NPrgvKF3EAQbjKKqamYzgK8E1M+pu2+leQ1cLyAvEFrk1ogL38p/9PPmeXfz90qJVmr/JkLnbni14XMiSOhh6MfSG3EHJAuo4a5+57LbMr2zBO58AuxyXyPpiExNaMC1Y6hJmQfxvPdDuZQlOKFGq9b0nYAWX+YUoysBhlrrCzE="
  # GITHUB_TOKEN
  - secure: "tRw6gcvznU3ivEou6HqrHC09Ke5ApgDaVslCiEl/SpalCZDVji8p8qJhXtGtha/hPWzYdTkOA9pbhwaryMiqGhpvVMeOl2EzKRV+n2yczkaBy+sbeZsRvsCPvIEZHfMABoZgdp8oDCYajj7wSyvYJpdSLoc6KzQJpzd47HoqDlefSP7DS8zA4fhw+N4AXt5hwezDyHzl3IAZrgak8a9CiTBfbjvR6SxpqULYtUe2CDjmQi/uDP8NIqkf2qByJACrfemUmDYuvxgrg/4L9Cpv8TcdFgRFaHeX2wlM5abPRoKEDDTSEinEyT63ZlYuNxlugtXUgnS6KAj7EIrfpCo7a6hpCV3/gOXkum82LW7tzEgeTmwPTJWsbwOdQgZMiQ0P/LHGsFMWoa6FH6HgYl8/be7R3oUiB1PSI4SGzxp/nG5kGTZTuIYtjef33H5nszxSJ8Kf23Ib6OI/pR/s2VKKixDila+xMEKD2oMHYIkCjIqVB/j9S0eRGYjjsk+8la6xY15kZwkvtiMyoTrWZ/NNdU8o0uYuutYyM2jnfcAJ57IXW81JieVwEvSwyTZgXcn0SHWw9cZ3Y0bkr1Ox1YeBVaGXJpU10oCXhlBnUNKBGNaM6yjx3IiHTqCo8hvObS0eUi7txrVjtZ+x83DrO/fsXCcnboUzjnFyna763QtvjY8="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs nhs.auth.web --details
  --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- "./bin/ci/push.sh"
